/**
 * PX /ns endpoint request
 *
 * Reversed from main.js line 8374-8409 (Am), call site line 10430-10438
 *
 * ═══ Input ═══
 *   uuid: String — session UUID (generated by Xa()), e.g. "68303b30-1224-11f1-a20a-312c66e49e40"
 *   host: String — /ns domain (optional, default "https://tzm.px-cloud.net")
 *
 * ═══ Original logic ═══
 *   Am(t, e):                        // t = Xa() = uuid, e = host
 *     url = e + "/ns?c=" + t         // "https://tzm.px-cloud.net/ns?c={uuid}"
 *     GET url (XMLHttpRequest, async, no credentials)
 *     200 → Sm = responseText
 *     record Performance duration → Em
 *
 *   Call site (main.js:10430-10438):
 *     a = "https://tzm.px-cloud.net"
 *     Am(Xa(), a)                    // first call
 *     setInterval(() => Am(Xa(), a), 60 * r * 1e3)  // periodic refresh
 *
 * ═══ Output ═══
 *   Promise<{ sm, duration, url }> — sm is Sm, placed into the Bundle #2 payload event field
 *   NOT the cs param! cs comes from the ob response handler (qa)
 *
 * Usage:
 *   const fetchNs = require('./ns')
 *   const { sm } = await fetchNs('68303b30-1224-11f1-a20a-312c66e49e40')
 */

const https = require('https');
const http = require('http');

function fetchNs(uuid, host) {
    if (!host) host = 'https://tzm.px-cloud.net';
    const url = host + '/ns?c=' + uuid;

    return new Promise((resolve, reject) => {
        const mod = url.startsWith('https') ? https : http;
        const start = Date.now();

        mod.get(url, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                const duration = Date.now() - start;
                if (res.statusCode === 200) {
                    resolve({ sm: data, duration, url });
                } else {
                    resolve({ sm: null, duration, url, status: res.statusCode });
                }
            });
        }).on('error', (e) => {
            resolve({ sm: null, duration: Date.now() - start, url, error: e.message });
        });
    });
}

module.exports = fetchNs;
