#!/usr/bin/env python3
"""
targets.py — validate catalog/targets.yaml (the target-coverage index) and render TARGETS.md.

  python catalog/targets.py --check     # validate + verify TARGETS.md is in sync (CI mode)
  python catalog/targets.py --write      # (re)generate TARGETS.md from targets.yaml
  python catalog/targets.py --render      # print TARGETS.md to stdout

Single source of truth: catalog/targets.yaml. TARGETS.md is generated — never hand-edit it.
Requires pyyaml: pip install pyyaml
"""
import glob
import os
import sys

try:
    import yaml
except ImportError:
    print("pyyaml is required: pip install pyyaml")
    sys.exit(2)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TARGETS_YAML = os.path.join(HERE, "targets.yaml")
TARGETS_MD = os.path.join(ROOT, "TARGETS.md")

REQUIRED = ["id", "name", "domain", "protection", "approach", "status", "assets", "summary"]
DOMAINS = {"android", "ios", "native", "windows", "web"}
APPROACH = {"pure-algorithm", "rpc-bypass", "env-patching"}
STATUS = {"in-repo", "in-repo+case", "pointer-only"}
ASSET_KINDS = {"skill", "case", "script", "tool", "pointer"}

STATUS_BADGE = {
    "in-repo": "🟢 in-repo",
    "in-repo+case": "🟢 in-repo + 🎬 case",
    "pointer-only": "🟠 pointer-only",
}
APPROACH_BADGE = {
    "pure-algorithm": "pure-algorithm",
    "rpc-bypass": "RPC bypass",
    "env-patching": "env-patching",
}


def load_catalog_ids():
    ids = set()
    for f in glob.glob(os.path.join(HERE, "*.yaml")):
        if os.path.basename(f) == "targets.yaml":
            continue
        doc = yaml.safe_load(open(f, encoding="utf-8")) or {}
        for e in doc.get("entries", []):
            if e.get("id"):
                ids.add(e["id"])
    return ids


def load_targets():
    doc = yaml.safe_load(open(TARGETS_YAML, encoding="utf-8")) or {}
    return doc.get("targets", [])


def validate(targets, catalog_ids):
    """Return (errors, warnings)."""
    errors, warnings, seen = [], [], {}
    for t in targets:
        where = f"targets.yaml:{t.get('id', '<no-id>')}"
        for k in REQUIRED:
            if k not in t or t[k] in (None, "", []):
                errors.append(f"{where}: missing field {k}")
        tid = t.get("id")
        if tid in seen:
            errors.append(f"{where}: duplicate target id")
        elif tid:
            seen[tid] = where
        if t.get("domain") not in DOMAINS:
            errors.append(f"{where}: invalid domain {t.get('domain')!r}")
        if t.get("approach") not in APPROACH:
            errors.append(f"{where}: invalid approach {t.get('approach')!r}")
        if t.get("status") not in STATUS:
            errors.append(f"{where}: invalid status {t.get('status')!r}")

        in_repo_assets = 0
        for a in t.get("assets", []):
            if a.get("kind") not in ASSET_KINDS:
                errors.append(f"{where}: asset has invalid kind {a.get('kind')!r}")
            ref = a.get("ref")
            if ref and ref not in catalog_ids:
                errors.append(f"{where}: asset ref '{ref}' is not a known catalog id")
            path = a.get("path")
            if path:
                in_repo_assets += 1
                if not os.path.exists(os.path.join(ROOT, path)):
                    errors.append(f"{where}: asset path '{path}' does not exist on disk")
            if a.get("kind") == "pointer" and not a.get("url"):
                errors.append(f"{where}: pointer asset has no url")
            if path and a.get("url"):
                warnings.append(f"{where}: asset has both path and url (use one)")

        # status consistency vs assets actually present in-repo
        status = t.get("status")
        if status == "pointer-only" and in_repo_assets:
            errors.append(f"{where}: status=pointer-only but {in_repo_assets} in-repo asset(s) present")
        if status in ("in-repo", "in-repo+case") and not in_repo_assets:
            errors.append(f"{where}: status={status} but no in-repo asset (path) present")
        if status == "in-repo+case" and not any(a.get("kind") == "case" for a in t.get("assets", [])):
            errors.append(f"{where}: status=in-repo+case but no asset of kind 'case'")
    return errors, warnings


def _asset_link(a):
    if a.get("path"):
        return f"[`{a['path']}`]({a['path']})"
    if a.get("url"):
        label = a.get("ref") or "external"
        return f"[{label} ↗]({a['url']})"
    return a.get("ref", "?")


def render(targets):
    n = len(targets)
    in_repo = sum(1 for t in targets if t["status"] != "pointer-only")
    pointer = sum(1 for t in targets if t["status"] == "pointer-only")
    lines = []
    lines.append("<!-- GENERATED by catalog/targets.py from catalog/targets.yaml — do not edit by hand. -->")
    lines.append("")
    lines.append("# 🎯 Target Coverage Index")
    lines.append("")
    lines.append("The single source of truth for **target-specific** reversing assets — answers")
    lines.append("\"have we already reversed target X, and where is it?\" before anyone starts new work.")
    lines.append("")
    lines.append("> Source: [`catalog/targets.yaml`](catalog/targets.yaml) · regenerate with")
    lines.append("> `python catalog/targets.py --write`. This is **not** the capability catalog")
    lines.append("> (generic tools/methodologies live in `catalog/android.yaml`, `web.yaml`, …).")
    lines.append("")
    lines.append(f"**{n} targets** — 🟢 {in_repo} in-repo · 🟠 {pointer} pointer-only (algorithm in an external repo, not bundled).")
    lines.append("")
    lines.append("| Target | Domain | Protection / SDK | Approach | Status | Assets |")
    lines.append("|---|---|---|---|---|---|")
    for t in sorted(targets, key=lambda x: (0 if x["status"] != "pointer-only" else 1, x["domain"], x["name"])):
        assets = " · ".join(_asset_link(a) for a in t["assets"])
        prot = t["protection"].replace("|", "\\|")
        row = (f"| **{t['name']}** | {t['domain']} | {prot} | "
               f"{APPROACH_BADGE.get(t['approach'], t['approach'])} | "
               f"{STATUS_BADGE.get(t['status'], t['status'])} | {assets} |")
        lines.append(row)
    lines.append("")
    lines.append("### Per-target detail")
    lines.append("")
    for t in sorted(targets, key=lambda x: x["name"]):
        aliases = ", ".join(f"`{a}`" for a in t.get("aliases", []))
        lines.append(f"- **{t['name']}** — {t['summary']}")
        if aliases:
            lines.append(f"  <br><sub>routing hints: {aliases}</sub>")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("<sub>🟠 pointer-only means the reversing exists in a first-party external repo but is")
    lines.append("not yet bundled in this project — a candidate to promote into `skills/`.</sub>")
    lines.append("")
    return "\n".join(lines)


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    targets = load_targets()
    catalog_ids = load_catalog_ids()
    errors, warnings = validate(targets, catalog_ids)
    rendered = render(targets)

    if warnings:
        print(f"⚠️  {len(warnings)} warning(s):")
        print("\n".join("  " + w for w in warnings))
    if errors:
        print(f"❌ targets.yaml: {len(errors)} issue(s):")
        print("\n".join("  " + e for e in errors))
        sys.exit(1)

    if mode in ("--render",):
        sys.stdout.write(rendered)
        return
    if mode in ("--write", "-w"):
        with open(TARGETS_MD, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(rendered)
        print(f"✅ wrote {os.path.relpath(TARGETS_MD, ROOT)} ({len(targets)} targets).")
        return
    # default: --check
    on_disk = open(TARGETS_MD, encoding="utf-8").read() if os.path.exists(TARGETS_MD) else None
    if on_disk != rendered:
        print("❌ TARGETS.md is out of sync with targets.yaml. Run: python catalog/targets.py --write")
        sys.exit(1)
    print(f"✅ targets index OK: {len(targets)} targets, TARGETS.md in sync.")


if __name__ == "__main__":
    main()
